config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'application#assignment'

  # TODO: route POST quizzes/<quiz-id>/scores to the create method in ScoresController
  resources :quizzes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  content    :string
#  answer     :boolean
#  quiz_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Question < ApplicationRecord
  belongs_to :quiz
end

app/models/quiz.rb
# == Schema Information
#
# Table name: quizzes
#
#  id              :integer          not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  title           :string
#  description     :text
#  high_score      :integer
#  high_score_user :string
#  image           :string
#
class Quiz < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :scores, dependent: :destroy
end

app/models/score.rb
# == Schema Information
#
# Table name: scores
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  points     :integer
#  player     :string
#  quiz_id    :integer          not null
#
class Score < ApplicationRecord
  belongs_to :quiz

  # TODO: add validation such that the player name is at least 1 character long
  # TODO: add validation such that points is a whole integer number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def assignment; end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ show edit update destroy ]

  # GET /quizzes or /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1 or /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes or /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to quiz_url(@quiz), notice: "Quiz was successfully created." }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to quiz_url(@quiz), notice: "Quiz was successfully updated." }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy!

    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: "Quiz was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quiz_params
      params.fetch(:quiz, {})
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_quiz
  skip_before_action :verify_authenticity_token

  # def create
  # TODO : Handle POST request to create a new score
  # end

  private

  def set_quiz
    # TODO : Set the @quiz instance variable
  end

  def score_params
    # TODO : Define and permit the score parameters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/application/assignment.html.erb
<style>
  body {
    background-color: #f8fafc;
  }
</style>

<article class="prose">
  <section>
    <h2>Assignment</h2>
    <p>Improve and work on the code you have been given such that your application looks and behaves similarly to the one shown and described below.</p>
    <p>We have already done a lot of the work. Do not let the images and videos intimidate you. Use the components and functions we have defined for you.</p>
    <p>We have added <code>TODO:</code>s where we think you should make changes.</p>
  </section>
  
  <section id="backend">
    <a href="#backend" class="no-underline">
      <h3># Backend (Ruby on Rails)</h3>
    </a>
    <div class="p-1 bg-slate-200 rounded-lg shadow-lg">
      <img src="/images/target_backend_preview.png">
    </div>
    <p>Notice that:</p>
    <ul>
      <li>The number of questions in the quiz is shown below the description</li>
      <li>Listing all scores on a quiz together with the player names</li>
    </ul>
    <p>Additionally:</p>
    <ul>
      <li>
        Create a method <code>create</code> that creates new scores in the <code>ScoresController</code> such that we can use it in our frontend.
        Route it such that we can make <code>POST</code> requests to <code>/quizzes/&lt;quiz-id&gt;/scores</code>.
      </li>
      <li>
        Add validation to the <code>Score</code> model such that the <code>player</code> name is at least 1 character long and <code>points</code> is a whole integer number.
      </li>
    </ul>
  </section>

  <section id="frontend">
    <a href="#frontend" class="no-underline">
      <h3>Frontend (Svelte)</h3>
    </a>
    <div class="p-1 bg-slate-200 rounded-lg shadow-lg">
      <video controls>
        <source src="/videos/target_frontend_preview.mov">
      </video>
    </div>
    <p>Notice that:</p>
    <ul>
      <li>The quiz is fetched from the backend.</li>
      <li>We remember what the user has answered and calculate the score by multiplying the number of correctly answered questions with one hundred.</li>
      <li>The player must write their name to be allowed to submit their score.</li>
      <li>We show the current question number in the top left corner.</li>
    </ul>
  </section>

  <section id="assets">
    <a href="#assets" class="no-underline">
      <h3>Assets</h3>
    </a>
    <p>All icons needed to complete this assignment are included.</p>
    <ul>
      <li>Cross icon</li>
      <li>Checkmark icon</li>
      <li>Hash icon</li>
      <li>Rocket icon</li>
    </ul>
  </section>

  <section id="delivery">
    <a href="#delivery" class="no-underline">
      <h2>Delivery</h2>
    </a>
    <p>Create a private GitHub repository and give John and Wahed access. Alternatively compress your code into an archive and send it back to us.</p>
    <p>Our Github usernames:</p>
    <ul>
      <li><code>johnro</code></li>
      <li><code>wahed-attensi</code></li>
    </ul>
  </section>

  <section id="good-luck">
    <a href="#good-luck" class="no-underline">
      <h2>Good luck!</h2>
    </a>
    <p>
      Try to implement as much as you can. Sprinkle on some animations if you have time.
      <b>Have fun.</b>
      It is not the end of the world if something does not work exactly like our previews.
    </p>
    <div class="flex justify-center">
      <div class="w-32 h-32 animate-bounce">
        <svg xmlns="http://www.w3.org/2000/svg" x="0" y="0" version="1.1" viewBox="0 0 500 500">
          <g id="background_achievement-15">
            <path fill="#ffd62c" d="M244.1 462.3 18.2 328.8c-7.2-4-13.4-10.7-6.4-15l226.7-130.7c3.4-2.1 8.6-3.5 12-1.5l237.2 137.6c7.2 4.2 8.5 15.9 1.3 20L273.9 462.1c-9.2 5.4-20.5 5.4-29.8.2z"/>
            <linearGradient id="SVGID_1_-achievement-15" x1="171.3625" x2="203.5925" y1="89.725" y2="138.065" gradientTransform="matrix(1 0 0 -1 0 502)" gradientUnits="userSpaceOnUse">
              <stop offset="0" stop-color="#ffd62c"/>
              <stop offset="1" stop-color="#9a433a"/>
            </linearGradient>
            <path fill="url(#SVGID_1_)" d="M149.3 362.3c-5.3-3.5-10.1-7.8-15.5-11.2l-42 21.3L228.2 453l39.6-26.3c-2.2-1.3-116.3-63-118.5-64.4z"/>
          </g>
          <g id="book_achievement-15">
            <path d="M354.7 376.2c.4 0 4.4-1.6 1.1-4.1-2.2-1.7-4.5-3.3-6.9-4.7" class="st2_achievement-15"/>
            <path fill="#ffe8bc" d="M354.7 355.2s-3.3 12.3 0 18.9l-45.3 26.6-44.8 25.9v-19.2"/>
            <path d="M356.2 353.2c-.1.9-.2 1.7-.3 2.6l-91.3 51.7v19.2l91.2-53.2v2.3L261 430.7v-26.1l95.2-51.4z" class="st2_achievement-15"/>
            <path d="m355.7 353.6-94.2 53.9-132.1-77.6 92.1-52.9c2.8-1.6 6.3-1.6 9.1.1l125 74.1c.7.4.9 1.2.5 1.9 0 .2-.2.4-.4.5z" class="st4_achievement-15"/>
            <path d="M261.1 430.6s-132-77.8-131.6-78.1 0-22.5 0-22.5l132.1 77.6-.5 23zM355.8 351.2c.8.6 1.3 1.4 1.4 2.4.2 1.6-1.5 2.4-2.1 2.7" class="st2_achievement-15"/>
            <linearGradient id="SVGID_00000019660554438947926090000007019875864816022192_-achievement-15" x1="208.4211" x2="243.6011" y1="136.0193" y2="188.7793" gradientTransform="matrix(1 0 0 -1 0 502)" gradientUnits="userSpaceOnUse">
              <stop offset="0" stop-color="#f26250"/>
              <stop offset="1" stop-color="#463f46"/>
            </linearGradient>
            <path fill="url(#SVGID_00000019660554438947926090000007019875864816022192_)" d="m203.7 321-45.1 26.1 67.1 39.3 51.1-29.4"/>
          </g>
          <g id="trophy_achievement-15">
            <path fill="#68e1fd" d="m133.6 206.4-8.6-8.7c-2-2-5.2-2-7.2 0s-2 5.2 0 7.2l8.7 8.6c2 2 5.2 2 7.2 0s1.9-5.1-.1-7.1zM113 223.4H99.1c-6.5 0-6.6 10.2 0 10.2H113c6.5 0 6.5-10.2 0-10.2zM134.2 245.6c-2-1.9-5.2-1.9-7.2 0l-9.2 9.2c-2 2-2 5.2 0 7.2s5.2 2 7.2 0l9.2-9.2c1.9-2 1.9-5.2 0-7.2zM343.2 253.9l8.7 8.7c2 2 5.2 2 7.2 0s2-5.2 0-7.2l-8.6-8.6c-2-2-5.2-2-7.2 0s-2.1 5.1-.1 7.1zM363.8 236.9h13.9c6.5 0 6.5-10.2 0-10.2h-13.9c-6.5 0-6.5 10.2 0 10.2zM342.6 214.6c2 1.9 5.2 1.9 7.2 0l9.2-9.2c1.9-2.1 1.8-5.3-.2-7.2-2-1.8-5-1.8-6.9 0l-9.2 9.2c-2.1 2.1-2.1 5.2-.1 7.2zM202.1 327.8v15.3s8.9 22.3 42.3 22.3 44.9-21.5 44.9-21.5v-14" class="st6_achievement-15 targetColor"/>
            <ellipse cx="245.8" cy="327.8" fill="#68e1fd" class="st6_achievement-15 targetColor" rx="43.6" ry="25.4"/>
            <ellipse cx="245.8" cy="327.8" fill="#463f46" opacity=".31" rx="43.6" ry="25.4"/>
            <path fill="#68e1fd" d="M230.4 295.8v17.7s4.1 7.5 16.1 7.5c11.9 0 14.8-8.6 14.8-8.6v-20.2M298.9 234.4l22.1 13.1s4.6 46.8-39.5 37.3l6.8-10.3s20.5 1.6 20.3-20.5l-11.9-6.2 2.2-13.4zM193.6 174.3l-21.8-12c-2.6.8-4.3 3.3-4.2 6 .2 4.8-1.6 34.4 24.9 61.6V211s-10.6-14.4-11.9-29.5l10.8 6.5" class="st6_achievement-15 targetColor"/>
            <path fill="#68e1fd" d="m189.4 186.6 4.9 69.7s6.9 41.5 51.5 41.5 51-41.1 51-41.1l6.6-70" class="st6_achievement-15 targetColor"/>
            <path fill="#463f46" d="M267.9 215.5s17.3-2.2 25.5-13.7c0 0-1.9 77-14.9 85.5s-15.6 11.4-40.8 10.3c0 .1 32-2.4 30.2-82.1z" opacity=".13"/>
            <ellipse cx="246.4" cy="186.6" fill="#68e1fd" class="st6_achievement-15 targetColor" rx="57" ry="32.8"/>
            <ellipse cx="246.4" cy="186.6" fill="#0d77a0" rx="57" ry="32.8"/>
            <ellipse cx="245.8" cy="186.5" fill="#023d4f" rx="45.8" ry="22.4"/>
          </g>
          <g id="character_achievement-15">
            <path d="m292.3 157.5 3.4-5.4s1-4.9 2.2-4.4.6 5.2.6 5.2 6.9-6.8 8.8-4.8 3 7.1 1.9 8.4-13.9 6.9-13.9 6.9M211.3 128.3l1.2-5.1s2.3-3.4 1.4-3.9-3.4 2.7-3.4 2.7 0-8.1-2.3-8.1-6 2.3-6.1 3.8 4 12.4 4 12.4" class="st11_achievement-15"/>
            <path d="M219.1 148.9c-.8-3.1-4.9-16.7-6.2-23-4.7-.7-7-.7-10 2.6 1.1 8.1 3.2 22.1 4.6 26.8 2.1 6.9 24.5 23.7 24.5 23.7l5.7-21.2s-17.6-4.9-18.6-8.9zM291.6 155.3s-15.7 18-20.2 18.3-14.4-9.5-14.4-9.5l-15.1-5.8c.1 6.8.2 13.5.1 20.3l12.7 5.4s6.7 8.9 16.7 9.7 28.3-29.2 28.3-29.2c-.3-3.4-8.1-9.2-8.1-9.2z" class="st4_achievement-15"/>
            <path d="M253.6 205.1s10.6-30.8 6.3-37.9-21.5-12.6-29.7-11.9-3 49.4-1.6 49.8 13.4 8.8 25 0z" class="st4_achievement-15"/>
            <path fill="#af2b38" d="M226.8 200.5v7.3s13.9 3.9 27.8 1.1l-.8-6.4c.1 0-10.9 5.6-27-2z"/>
            <path d="M231.1 143s0 18 6.6 19.2c7.3 1.3 11.3-7 11.3-7s.9-15.9-6.3-17.3-11.4 2.8-11.6 5.1z" class="st11_achievement-15"/>
            <path d="M231.9 145.2c-2.2-.6-4.9-1.3-6.3-3.4-2-3.2.2-6.5 2.9-8.4 3.2-2.2 7.2-3 11-2.1 5.2.9 12.5 3.1 13.9 8.9 2 8.1-5.8 18.2-5.8 18.2v-5s2.6-3.3 1.2-4.6-1.9 1.8-1.9 1.8.6-6-3.7-6.6c-1.8-.3-2.4.7-3.8 1.5-1 .5-2.1.7-3.2.6-1.4-.1-2.9-.4-4.3-.9z" class="st2_achievement-15"/>
          </g>
        </svg>
      </div>
    </div>
  </section>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AttensiCase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="container mx-auto mt-28 p-5 flex">
      <%= link_to(quizzes_path) do %>
        <h1 class="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">Colourful</span>Quizzes</h1>
      <% end %>
    </header>
    <main class="container mx-auto  p-5 flex rounded-lg">
      <%= yield %>
    </main>
  </body>
</html>

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz) do |form| %>
  <% if quiz.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
        <% quiz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/_quiz.html.erb
<div class="w-1/3 bg-emerald-50 rounded-md m-2 p-5">
  <h3 class="text-3xl font-bold dark:text-white py-2"><%= @quiz.title %></h3>
  <h4 class="text-xl font-medium text-slate-600 dark:text-white"><%= @quiz.description %></h4>
  <!-- TODO: show the number of questions in the quiz in a human friendly way -->
  <h6 class="text-md font-medium text-slate-600 dark:text-white"></h6>

  <ul class="mt-5">
    <% @quiz.questions.each do |question| %>
      <li>
        <div class="p-4 mb-4 text-sm text-slate-800 rounded-lg bg-gradient-to-r to-emerald-200 from-sky-200 dark:bg-gray-800 dark:text-blue-400">
          <div class="font-medium text-xs">True/False question</div>
          <span class="font-medium text-lg"><%= question.content %></span>
          <div>
            <% if question.answer == true %>
              <span class="bg-green-200 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-blue-900 dark:text-blue-300">Correct</span>
            <% else %>
              <span class="bg-red-200 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-blue-900 dark:text-blue-300">Incorrect</span>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<div class="w-2/3 bg-yellow-50 rounded-md m-2 px-5 py-5">
  <h1 class="flex items-center text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r to-orange-700 from-yellow-400">
    Leaderboard
    <span class=" text-2xl font-semibold me-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ms-2">
      <svg class="w-50 h-50  text-yellow-500 bg-gradient-to-r to-yellow-200 from-yellow-400 rounded-full m-1 p-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" viewBox="0 0 24 24">
        <path d="M13.849 4.22c-.684-1.626-3.014-1.626-3.698 0L8.397 8.387l-4.552.361c-1.775.14-2.495 2.331-1.142 3.477l3.468 2.937-1.06 4.392c-.413 1.713 1.472 3.067 2.992 2.149L12 19.35l3.897 2.354c1.52.918 3.405-.436 2.992-2.15l-1.06-4.39 3.468-2.938c1.353-1.146.633-3.336-1.142-3.477l-4.552-.36-1.754-4.17Z"/>
      </svg>
    </span>
  </h1>
  <% if @quiz.scores.empty? %>
    <h3 class="text-lg text-yellow-600">Highscores will appear here</h3>
  <% else %>
    <ul class="mt-5">
      <!-- TODO: List the highscores here along with player names and points -->
    </ul>
  <% end %>
</div>


 

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Show this quiz", @quiz %> |
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/index.html.erb
<div class="flex items-center p-5">

  <div class="">
    <h3 class="text-3xl font-bold dark:text-white py-5">Viewing Quizzes</h3>
    <h6 class="text-lg font-bold dark:text-white"><%= pluralize(Quiz.all.count, 'Quiz') %></h6>


    <% Quiz.all.each do |quiz| %>
        <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 w-50 m-2">
            <img class="h-auto max-w-full rounded-t-md" src="<%= quiz.image %>"/>
            <div class="p-5">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= quiz.title %></h5>
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= quiz.description %></p>
                <%= link_to(quiz_path(quiz)) do %>
                  <button type="button" class="text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">View</button>
                <% end %>
                <a target="_blank" href="<%= "http://localhost:5173/#{quiz.id}" %>">
                  <button type="button" class="text-white bg-gradient-to-br from-red-600 to-purple-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">Play</button>
                </a>
            </div>
        </div>
    <% end %>
  </div>
</div>

app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quiz %>

<div class="hidden">
  <%= link_to "Edit this quiz", edit_quiz_path(@quiz) %> |
  <%= link_to "Back to quizzes", quizzes_path %>
  <%= button_to "Destroy this quiz", @quiz, method: :delete %> 
</div>